### ISSUE TITLE
Shortcut for comments

### ISSUE THREAD

**Issue by dario2994** [gphalkes/tilde#1]
It would be brilliant to have a shortcut (default _ctrl+e_ ?) to comment or uncomment a line (or a bunch of selected lines).

**Comment by gphalkes** [comment]
I've finally gotten around to implementing this. This will be part of the next release. (It will use ctrl+/ as the short-cut)

**Comment by gphalkes** [comment]
Just to let you know that I've released a new version of Tilde, which should fix this issue.
