### ISSUE TITLE
Compiling on raspberry pi, t3shared works, but produces unusable binary

### ISSUE THREAD

**Issue by ulno** [gphalkes/tilde#10]
I am trying to build tilde for the raspberry pi.
I installed libtranscript and LLnextgen  manually successfully and can now run the whole t3shared make process.
However, there is not install option in t3shared and the only possible binary I can find is in tilde/src/.objects: edit

Running this just shows: Debug mode: setting VM limit

Is there anywhere some more information how the actual package build process works (I will probably now try to understand the Arch AUR pkgbuild process and try to apply it for raspbian)?

**Comment by gphalkes** [comment]
Sorry for not getting back to you earlier. The process building using makefiles you describe is the development build process, which does indeed only build the tilde/src/.objects/edit binary. Hence the message about Debug mode that you saw.

The release builds are done with Makefiles generated from the files in the dist subdirectories. However, this requires some scripts I have not put up on github yet. What you probably want to try though is to build the latest released version (which can be found on http://os.ghalkes.nl/tilde). The tarballs released there contain the release Makefiles.

That said, the Debug binary should however still run normally. Does the program exit after showing the message? Or does it just hang?

**Comment by ulno** [comment]
Sorry, I was also on the road for a while and had to use a heavily customized mcedit unfortunately... ok, back to tilde.

I just took another look, and got the before-mentioned debug message several times, and resulting in a direct termination after showing it. I started several times more resulting in weird letters on the screen and termination, and started again and tilde came up and seems to work fine (also mouse and and ctrl-keys + selcection works).

Weird letter starts look like this:
```
133 pi@ulnoiotgw:~/src/tilde/src/.objects$ ./edit

Abortedrtual method called
134 pi@ulnoiotgw:~/src/tilde/src/.objects$ 4R3R2R3R2R2R3R3R3R5R3R2R2R2R
```

So I assume something weird with the terminal emulation is going on. I am accessing the pi via ssh and running inside byobu (tmux), however, I have also now tried, running in plain bash in ssh - getting about the same results.

Exiting a "working" tilde shows: 
```
*** Error in `./edit': munmap_chunk(): invalid pointer: 0x012565f0 *** 
Aborted
```
After this I cannot start tilde anymore and it alway shows the garbled weird letters and Abortedrtual - also when trying different terminals and running outside of tmux/byobu. (It also showed Segmentation fault once).

Strangely, when using ``strace ./edit 2> log``, tilde always starts. It seems also to start most times without ``2> log`` only using strace -> heisenbug?

String only ./ edit now usually shows the before-mentioned error message.

Any other ideas what I should test?

**Comment by ulno** [comment]
Using the release packages from dist and compiling and installing them in the right order results in a usable binary on the raspberry pi. I will try to create a script which downloads and compiles them automatically and augment the thread here, when this is done.

**Comment by ulno** [comment]
If somebody else wants to compile tilde in a debain-like arm environment, you can base your work on this script here:
https://github.com/ulno/ulnoiot/blob/master/bin/install_tilde

Or you can read the related blog-post here:
https://ulno.net/blog/2017-07-12/comfortable-command-line-editors-for-single-board-computers-for-teaching-iot/

**Comment by gphalkes** [comment]
Thanks for figuring this out. The Makefiles in the project are the development makefiles, and may make assumptions on the underlying system that don't hold for Raspberry Pi's :-(

**Comment by marktyers** [comment]
Hi, the link to your install_tilde script is no longer working, any chance you can update this?
Cheers,

**Comment by ulno** [comment]
Use this one here, I reworked it a bit. You can toss most of the ulnoiot-related stuff in the beginning, then the script should compile.

https://github.com/ulno/ulnoiot/blob/master/bin/install_tilde_release
