### ISSUE TITLE
Right click ...

### ISSUE THREAD

**Issue by stuaxo** [gphalkes/tilde#12]
Hi,
   Right click is eaten by the editor, which is kind of expected - but it means I can't right click and use my terminal emulators menu.

It would be good if either right click could be passed through, alternately tilde could have a popup menu, e.g. -

```
Cut
Copy
[Paste]
Paste To New File
```

**Comment by gphalkes** [comment]
Enabling mouse support on a terminal is unfortunately an all-or-nothing deal. Typically the terminal provides access to the functions it normally provides by adding a modifier (e.g. for XTerm, pressing shift while pressing the mouse buttons will always result in the XTerm mouse action).

Having a right-click popup menu would be a nice addition to Tilde.

**Comment by pepa65** [comment]
On my terminal (Sakura) on Ubuntu 16.04 the terminal's right-click menu works fine when using tilde. (I personally would not like any other behaviour...)

**Comment by magiblot** [comment]
I see this has finally been added. Awesome!

![screenshot_20181223_184308](https://user-images.githubusercontent.com/20713561/50386224-fee05100-06e2-11e9-81b8-5d9aaad81028.png)

As a small suggestion, I think it would be much more comfortable if the popup menu could be dismissed just by cliking again on the same place where right-click was performed, that is, the popup's border.

**Comment by magiblot** [comment]
Of course, but my point was being able to dismiss it without having to move the pointer at all. I think that's the most important for usability.

**Comment by gphalkes** [comment]
Thanks for the suggestion. Being able to dismiss without moving the cursor does seem like a good tweak to the behavior.

**Comment by gphalkes** [comment]
Fixed the behavior of menus to close when clicked on the border (https://github.com/gphalkes/t3widget/commit/b6d36bd5fbc5b34d56768f6fa7562decea61ded6). This makes it possible to dismiss the right-click menu without moving the mouse cursor.

This will be part of the next libt3widget release.

**Comment by magiblot** [comment]
Thank you!
