### ISSUE TITLE
Online chat support channel for tilde

### ISSUE THREAD

**Issue by ulno** [gphalkes/tilde#15]
Does or should tilde have an online chat-room? I am happy to create a matrix or IRC channel for it (and hang out there to give the little of support I can give).

**Comment by gphalkes** [comment]
Tilde does not have an online chat room. I myself don't have much time to provide support, my time to spend on tilde is rather fragmented. But it may indeed be good to have some more direct user support. Feel free to start a channel. I'll advertise it on the homepage, and in the README for the tilde repository (which I will create shortly)

**Comment by ulno** [comment]
I created a #tilde channel on freenode IRC. I hope it worked, please feel free to check. I should be logged in from matrix/riot there as ulno.
