### ISSUE TITLE
Ctrl+k aka kill line

### ISSUE THREAD

**Issue by terba** [gphalkes/tilde#16]
This is what i'm missing the most: shortcut to delete the current line.

**Comment by gphalkes** [comment]
That is indeed a practical one. I'll keep the bug open to remind me about the feature request.

**Comment by gphalkes** [comment]
Implemented in https://github.com/gphalkes/t3widget/commit/f73a65fce19037b09c962782271e1da20e6f5444. There will be some work to add it to the Tilde menus, but with the next release of ilbt3widget, Tilde will accept ctrl-k to delete the current (or all selected) line(s).

**Comment by terba** [comment]
Thank you!
