### ISSUE TITLE
Error: libt3key: Permission denied

### ISSUE THREAD

**Issue by mironx** [gphalkes/tilde#24]
I got this message after installation:
![obraz](https://user-images.githubusercontent.com/476990/36064076-e90caece-0e85-11e8-9d0b-f8b099cfe42c.png)

Ubuntu Server 16 with latest updates.
Thank you for help.

**Comment by mironx** [comment]
With sudo is working.

**Comment by gphalkes** [comment]
Can you please provide details on how you installed (official source release, github repositories, the binary package repositories linked from the tilde page)? Further it would be helpful to provide the value of the TERM variable (`echo $TERM`) and the output of `ls -l /usr/share/libt3key1`

Thank you.

**Comment by mironx** [comment]
Here you are:
1. I downloaded package from: https://os.ghalkes.nl/tilde/download.html
2. TERM
```
dev@dockerrepo:~$ echo $TERM
xterm-256color
```
3. libt3key1
```
dev@dockerrepo:~$ ls -l /usr/share/libt3key1
total 80
-rw-r--r-- 1 root root  3822 Feb  4 11:00 Eterm
lrwxrwxrwx 1 root root     5 Feb  4 11:00 Eterm-256color -> Eterm
lrwxrwxrwx 1 root root     5 Feb  4 11:00 Eterm-88color -> Eterm
lrwxrwxrwx 1 root root     5 Feb  4 11:00 Eterm-color -> Eterm
-rw-r--r-- 1 root root  1156 Feb  4 11:00 kterm
-rw-r--r-- 1 root root  2077 Feb  4 11:00 linux
-rw-r--r-- 1 root root 12149 Feb  4 11:00 mlterm
lrwxrwxrwx 1 root root     6 Feb  4 11:00 mlterm-256color -> mlterm
-rw-r--r-- 1 root root  1622 Feb  4 11:00 putty
-rw-r--r-- 1 root root  3682 Feb  4 11:00 rxvt
lrwxrwxrwx 1 root root     4 Feb  4 11:00 rxvt-16color -> rxvt
lrwxrwxrwx 1 root root     4 Feb  4 11:00 rxvt-256color -> rxvt
lrwxrwxrwx 1 root root     4 Feb  4 11:00 rxvt-88color -> rxvt
lrwxrwxrwx 1 root root     4 Feb  4 11:00 rxvt-color -> rxvt
-rw-r--r-- 1 root root  9371 Feb  4 11:00 rxvt-unicode
-rw-r--r-- 1 root root  8103 Feb  4 11:00 screen
-rw-r--r-- 1 root root   607 Feb  4 11:00 st
-rw-r--r-- 1 root root 22366 Feb  4 11:00 xterm
lrwxrwxrwx 1 root root     5 Feb  4 11:00 xterm-16color -> xterm
lrwxrwxrwx 1 root root     5 Feb  4 11:00 xterm-256color -> xterm
lrwxrwxrwx 1 root root     5 Feb  4 11:00 xterm-88color -> xterm
lrwxrwxrwx 1 root root     5 Feb  4 11:00 xterm-color -> xterm
```

**Comment by gphalkes** [comment]
Hmm, that all looks perfectly normal. Could you run the following command:

`strace -o /tmp/strace.txt tilde`

as non-root user and attach the created file (`/tmp/strace.txt`) to this bug? That should allow to determine what exactly the permissions are failing on. You will probably have to install `strace` to make it work though.

**Comment by mironx** [comment]
Here you are:
[strace.txt](https://github.com/gphalkes/tilde/files/1714680/strace.txt)

**Comment by gphalkes** [comment]
This is the line which is important:

`open("/home/dev/.local/share/libt3key/linux", O_RDONLY) = -1 EACCES (Permission denied)
`

It seems somehow the dev user doesn't have access to the named file, or more likely one of the directories on that path. This is an unusual situation, and you probably want to change that.

That is not to say that the behavior of Tilde is correct in this case. It certainly should not bail out just because it doesn't have access to a local overrides file.

**Comment by gphalkes** [comment]
This should be fixed in the next release https://github.com/gphalkes/t3config/commit/9001ee6348544094efb55f02a009df25a3613f18
