### ISSUE TITLE
F8 and S-F8 short cut is not working

### ISSUE THREAD

**Issue by mironx** [gphalkes/tilde#25]
It looks F8 and S-F8 short cut is not working.
Ubuntu Server 16 with latest updates.
I have installation on Virtual Box (Host Key is F12).
Generally in other programs and in Ubuntu is every thing working ok.

**Comment by gphalkes** [comment]
Could you provide the value of the TERM environment variable (`echo $TERM`) and what appears on the screen if you press F8 while you are running `cat`? The latter should look something like `^[[19~` or similar.

**Comment by gphalkes** [comment]
That is really strange. But it may have something to do with the libt3key problems that you are experiencing. Let's attempt to figure out those first, and see if that resolves this as well.

**Comment by gphalkes** [comment]
OK, this is an issue with the latest libt3widget release. I somehow managed to mess up the key bindings. This is fixed in the latest commit (https://github.com/gphalkes/t3widget/commit/83dbe1bbd0f820114ebb3f17f6f1069dcce0d466) and I'll release a new version shortly.

Thank you for reporting!

**Comment by gphalkes** [comment]
This is fixed in the libt3widget 0.6.1.

**Comment by mironx** [comment]
I have tested right now. Now is working perfectly. Thank you.
