### ISSUE TITLE
Tilde freezes on terminal clipboard insert

### ISSUE THREAD

**Issue by terba** [gphalkes/tilde#26]
Tilde 0.4.0 running on Centos 7 in an ssh session in xterm freezes when I paste text with Shift+insert or Shift+MiddleClick. The pasted text appears but tilde freezes immediately and uses the CPU on 100%. X11 forwarding is disabled. The problem was introduced with the release 0.4.0.

**Comment by gphalkes** [comment]
Thank you for reporting this issue. I don't know how this issue slipped through testing, but it did. Bug is fixed in https://github.com/gphalkes/t3widget/commit/d87a2bb4ed80835a364a88a65e561f267cfc8098. I'll try to release this as soon as possible.
