### ISSUE TITLE
Add Goto Top and Goto End on ^Home and ^End keys

### ISSUE THREAD

**Issue by cheapy** [gphalkes/tilde#30]
It would just be more like Notepad, Notepad++, Midnight Commander and Norton Commander if those keystrokes worked.

I was able to get it working with a few lines of code by calling the existing routine with 1 for top and 9999999 for end, based on the assumption nobody would be editing a file larger than 10 million lines.

I would be happy to share the code.

**Comment by terba** [comment]
This is working already on my machines with tilde 0.3.7 and 0.4.0. Hitting Ctrl+Home places the cursor at the beginning of the file, Ctrl+Home at the end.

**Comment by gphalkes** [comment]
@cheapy If I understand correctly from the IRC channel conversation, you are using mrxvt-mini as your terminal emulator. I checked and found that mxrvt in its different variations, is reporting itself as rxvt, but producing different keyboard sequences for some of the keys, including Ctrl-Home and Ctrl-End. I've updated libt3key to include these sequences, so if you are using the latest libt3key (0.2.9) you should find that the behavior of Tilde is already what you want. (To check the version you are using, you can run tilde --version.)

Should this still not be working, even with libt3key 0.2.9, please file another bug.

**Comment by cheapy** [comment]
I recloned and recompiled and ^Home and ^End now work fine.

Thanks much!
