### ISSUE TITLE
(Suggestion) Mouse scrolling in tty

### ISSUE THREAD

**Issue by magiblot** [gphalkes/tilde#32]
Hi, I don't know it this would be very hard to implement, but I think it would be very nice to have support for mouse scrolling in tty (linux) console (through gpm, I guess).

I also take the opportunity to thank you for this awesome, great application. Thanks.

**Comment by gphalkes** [comment]
Thanks for pointing out that I had missed to implement this. I have fixed this in libt3widget commit https://github.com/gphalkes/t3widget/commit/b99e8caecf5a4115b6d25e6b501dc97dbc94a690. Note that I'm currently busy reworking much of the libt3widget API, which means I don't have much time to do much else on Tilde at the moment, and it may be some time before the next release.
