### ISSUE TITLE
"Shift-ins" Copy and paste inserts extra whitespace, needs "bracketed paste"

### ISSUE THREAD

**Issue by battaglia01** [gphalkes/tilde#35]
When copying and pasting into the editor, if you use the built-in Ctrl-C and Ctrl-V, everything works OK. But if you use the terminal's based Shift-Ctrl-V or Shift-Ins command, which usually lets you paste anything into the terminal, you get a bunch of extra whitespace. For instance: copy and paste the following into tilde

```
def foo():
  print("foo")
  print("bar")
  print("foobar")
```

If you do that with Ctrl-V, you get the right thing, but if you do it with Shift-Ins or Ctrl-Shift-V, you get

```
def foo():
  print("foo")
    print("bar")
      print("foobar")
```

This is because the terminal simply replays the text you typed as though you typed it, so it auto-indents and then double-indents everything.

Emacs has this working with their "bracketed paste mode:" https://debbugs.gnu.org/cgi/bugreport.cgi?bug=19093
Also works with micro as well, so this is possible to do.

I'm using KDE Neon (based on Ubuntu Xenial), running tilde on bash. Here is my version:
```
Tilde version 0.4.2
Copyright (c) 2011-2018 G.P. Halkes
Tilde is licensed under the GNU General Public License version 3
Library versions:
  libt3config 0.2.11
  libt3highlight 0.4.5
  libt3key (through libt3widget) 0.2.9
  libt3widget 0.6.3
  libt3window 0.3.0
  libtranscript 0.3.3
  libunistring 0.9.?
```

**Comment by gphalkes** [comment]
Thanks for reporting this issue. Bracketed paste mode was implemented for Tilde in version 0.6.0 of libt3widget. However, as you discovered, it was not actually working properly. The fix has been submitted in libt3widget (https://github.com/gphalkes/t3widget/commit/5d39e6bc3b1c3e23430efa424fe60588b1d16213), and a release will follow shortly.

**Comment by battaglia01** [comment]
Thanks. If I am using a package manager (on Ubuntu here) what is the best way to do this? I initially followed the instructions here: https://os.ghalkes.nl/tilde/download.html

**Comment by gphalkes** [comment]
If you used the instructions you mention, you should get the package update automatically as part of the regular ubuntu updates. If you want to speed up the process, you could run 'sudo apt-get update ; sudo apt-get upgrade' (or do the equivalent using the GUI tools).

(The package is now available in those repositories)
