### ISSUE TITLE
Building from Release archive

### ISSUE THREAD

**Issue by pepa65** [gphalkes/tilde#38]
Using Ubuntu MATE 18.04.1
When I want to have a more recent version than the Ubuntu repo (0.4), how do I build the release? I know how to build from current git; is building from the release archive the same?? The instructions are specifically about git, but I thought I'd try the release.

**Comment by gphalkes** [comment]
The instructions for the release are simpler. It is simply the standard ./configure ; make ; make install sequence that is normal for building software on Linux. The dependencies are the same as for the git build. Of course the libraries need to be build in the correct order, as with the git build (i.e. transcript  t3config t3key t3highlight t3window t3widget tilde), but you can skip the ones that are already up-to-date in Ubuntu as long as you have the development packages installed.

Alternatively, you could use the dsc files from Ubuntu cosmic to build local up-to-date packages.

There are of course also the repositories available on the Open Build Service that I maintain (linked from the os.ghalkes.nl/tilde website), that would keep you up-to-date with the latest releases.

**Comment by gphalkes** [comment]
Releases can be found at the official Tilde website: https://os.ghalkes.nl/tilde (and for the support libraries see https://os.ghalkes.nl/t3)

**Comment by pepa65** [comment]
Those are different release files than the ones on github.
But I've given up going this route, it is not easier at all, having to manually hunt down either binary releases through the Ubuntu repo, or discovering that in some cases the version is not high enough, then basically having to build all the t3 dependencies by hand...
The git build was much easier, just one script and it all was built afresh.
