### ISSUE TITLE
A few mouse issues in TTY

### ISSUE THREAD

**Issue by magiblot** [gphalkes/tilde#39]
Hi gphalkes, excuse me again for bothering during the holidays but I insist there is no need at all to rush. Anyway, I experienced a few non-critical issues related to the mouse while using tilde in the TTY and I thought it best to gather them in a single issue report. Here they are:

(I also recorded them here:
https://drive.google.com/open?id=1zjHKYmcgR36voWHIo7LK0w7qxOydwRk2)

- Suspended tilde keeps grabbing mouse. To reproduce, first make sure you can select text in bare TTY with the mouse. Then run tilde and suspend it, and try again to select text. This time you can't, because tilde is still grabbing the mouse input. If you then run another application with mouse support, it will work fine: it's only the console that's affected. Depending on what you do, you'll be able to see tilde performing all the mouse actions at once when resuming its execution.

- Mouse pointer freezes or disappears when holding left click and moving around. There seem to be three different situations:
1. When selecting text in a document, only the 'selection cursor at end/start' is shown, which is fine.
2. When attempting to select text in an empty area of a document (e.g. a new document), the pointer doesn't seem to be moving even though it actually is. (This also happens if you suspend tilde and attempt to select text from the console display).
3. When browsing the menus by holding the left mouse button pressed, the pointer becomes invisible and the only indicator of the mouse position is the highlighting of the menu entries.

- In the 3rd case from the previous point, one would think moving the mouse to the top left corner and then moving to the sides would result in the menu tabs being highlighted. However, they don't, since the mouse seems to have one row of space above the screen.

If you ask me, the only one which may be annoying is the pointer disappearing when browsing the menus. The other ones can barely be noticed.

Thank you very much!

**Comment by gphalkes** [comment]
The first issue you mention should be fixed in commit https://github.com/gphalkes/t3widget/commit/bdab583739842658c6905eaa0338cd36598bafc2.

The missing mouse pointer should be fixable, but will be somewhat tricky (notes for fixing: need to call Gpm_DrawPointer and set gpm_visiblepointer, but this needs to be done at the right time, i.e. on screen update)

I haven't looked into the issues with the menus yet.

**Comment by gphalkes** [comment]
As of commit https://github.com/gphalkes/t3widget/commit/402b322e6f699c177f486a446b2d56f234ca6c95 the remaining issues should be fixed. They will be included in the next release, which will be done soon.

Thanks for the very detailed bug report! Having such detail makes it much easier to debug the issues.

**Comment by magiblot** [comment]
Awesome! Thank you very much 😊
