### ISSUE TITLE
"Open Recent" file list is not preserved between two tilde sessions

### ISSUE THREAD

**Issue by tjaacks** [gphalkes/tilde#44]
I am running tilde 1.0.1 on a Ubuntu 16.04 machine, which I am accessing via SSH using KiTTY from Windows.

When I open and close a file in tilde, I can re-open it easily using "Open Recent" from the "File" menu. When I restart tilde, the file list there is empty. Is this intended or a bug?

I would love to have the recent file list saved, so that I can return to my last file after restarting tilde.

**Comment by gphalkes** [comment]
It was intended when I first implemented this. However, I agree that it would be better to save the list, although that is not quite as simple as it may sound as there may be multiple instances of tilde running simultaneously. I'll keep this bug open as a feature request.

**Comment by gftimjaacks** [comment]
Thanks for your quick reply. I see the problem, however, how do you deal with the config file in case of multiple instances? Doesn't the same problem appear there as well?

**Comment by gphalkes** [comment]
This is now implemented, and will be part of the next Tilde release.

**Comment by tjaacks** [comment]
Great, thank you very much!

**Comment by tjaacks** [comment]
Hmm, this obviously did not go into the 1.0.2. release. When is the next release planned?

**Comment by gphalkes** [comment]
You are absolutely right. I found a bug in Tilde that warranted a separate quick release. The feature will be in the next release, which I will do in the next week or two. It mostly depends on what other things I have time to implement in the near future. Given the time investment of a new release, I prefer to bundle multiple changes into a new release.

**Comment by tjaacks** [comment]
That sounds reasonable. Thanks for your work and the quick reply. :-)

**Comment by gphalkes** [comment]
This is now released as part of version 1.1.0
