### ISSUE TITLE
Feature request: system-wide default configuration

### ISSUE THREAD

**Issue by tjaacks** [gphalkes/tilde#45]
I'd like to have a system-wide default configuration for tilde, which gets loaded if no user-configuration file exists yet (e.g. for color scheme and tab size). I tried putting these configuration options in `/user/share/tilde/base.config`, but unfortunately they are not picked up because they are not allowed in `base_config.schema`.

Why not allow all user configuration fields in the `base.config` as well? Both files (`base.config` and `~/.config/tilde/config`) could use the same schema in my opinion.

**Comment by gphalkes** [comment]
You are absolutely right, there is no need to keep these configurations separate. The next Tilde release merges the schema and uses the same for both.

**Comment by tjaacks** [comment]
Thanks a lot for implementing this!

**Comment by tjaacks** [comment]
Great, thanks a lot!
