### ISSUE TITLE
Arrow keys & page up / down will not allow you to navigate around the document

### ISSUE THREAD

**Issue by Michaelinsurrey** [gphalkes/tilde#49]
Tilde 0.4.0 on Linux mint Mate edition 19.1 Tilde works perfectly.
However running :-
Tilde 1.0.0 on Raspberry Pi 4 running Raspbian (Debian 10 Buster), installed using Noobs 3.1.1, with the default terminal LXTerminal 0.3.2

You can navigate around the document using a mouse, but the arrow keys, & page up / down do not move the cursor.

pi@raspberrypi:~ $  tilde --version
Tilde version 1.0.0
Copyright (c) 2011-2018 G.P. Halkes
Tilde is licensed under the GNU General Public License version 3
Library versions:
  libt3config 0.2.11
  libt3highlight 0.4.6
  libt3key (through libt3widget) 0.2.9
  libt3widget 1.0.3
  libt3window 0.3.2
  libtranscript 0.3.3
  libunistring 9.10.?

**Comment by gphalkes** [comment]
That is annoying indeed. Does it work with other terminal emulators on the Raspberry Pi? I don't have the possibility to test this myself at the moment. Can you perhaps post what "echo $TERM" outputs and what appears on the screen when you run "cat" and then while it is running press the arrow and page up/dn keys? (It should be something like ^[[D for each key.)

**Comment by gphalkes** [comment]
This appears to be caused by LXterminal not being quite compatible with Xterm, even though it identifies as such to Tilde. Commit https://github.com/gphalkes/t3key/commit/bc36a3d96a15106b890a87cfc5090093e9d5ba9c in libt3key works around the problem by putting a few keys in the keymap used by Tilde.
