### ISSUE TITLE
Background colours not read correctly from config

### ISSUE THREAD

**Issue by seivadnomis** [gphalkes/tilde#5]
Tilde is excellent – just what I've been looking for. One small problem: I configured it to use my own choice of background colours, and then found that most of these were reverting to black when I next ran Tilde.

This seems to be down to a small typo in `attribute_string_to_bin()`: `if (strncmp(attr, "bg", 3) == 0)` will always fail because it's missing a space after `bg`. The result is that Tilde fails to load any background colour other than the ten basic ones listed in `attribute_map`.

**Comment by gphalkes** [comment]
Just to let you know that I've released a new version of Tilde, which should fix this issue.

**Comment by seivadnomis** [comment]
Many thanks. I can confirm the issue is now fixed.
