### ISSUE TITLE
Bug "go to matching brace" not working correctly

### ISSUE THREAD

**Issue by clhess** [gphalkes/tilde#50]
I was editing a perl file and had a function I was editing and tried to go to the end of the function by the matching brace... this did not work.

1.sub parseFileLines
2.{
3.  my (@lines) = @{$_[0]};
4.  $test = 0;
5.}

if i did goto matching brace on line 2, it would go to the end of line 3 instead of line 5

**Comment by gphalkes** [comment]
It appears the highlighting for the expression @{$_[0]} is broken. It doesn't consider the [0]} part of the expression, therefore when searching for the matching brace from line two, it finds this one. I'll have to dig into the syntax for perl and the highlighting patterns to see what is going on there.

**Comment by gphalkes** [comment]
This should be improved in commit https://github.com/gphalkes/t3highlight/commit/10ab218bee446841e68a16125cfb80a81e1485ed. I think there will still be some cases where the highlighting will not do what it is supposed to, but the rules for perl identifiers and variable references are very complex to capture correctly.

This fix will be part of the next t3highlight release (although if you wish to have the fix right away, you can just download the file here: https://github.com/gphalkes/t3highlight/blob/10ab218bee446841e68a16125cfb80a81e1485ed/src/data/def/perl.lang and put that in /usr/share/libt3highlight2/def/perl.lang).
