### ISSUE TITLE
Feature request: Markdown syntax highlighting

### ISSUE THREAD

**Issue by nevillepark** [gphalkes/tilde#51]
Markdown is a lightweight markup language that can easily be converted to HTML. Github, for example, uses Markdown. It would be nice to have this in tilde.

I've tried to make the highlight definitions myself, but I am very bad at it. 

[These regexes](https://gist.github.com/jbroadway/2836900) might be useful?

**Comment by gphalkes** [comment]
This would indeed be useful. When I have time, I'll have a look into making this.

**Comment by gphalkes** [comment]
Implemented in libt3highlight commit https://github.com/gphalkes/t3highlight/commit/56f311e29ec91d10420e322a8d5d3f340b198178.

This will be part of the new libt3highlight release.
