### ISSUE TITLE
Some extra keys for TUI navigation

### ISSUE THREAD

**Issue by stuaxo** [gphalkes/tilde#52]
Here are some keyboard interactions that would be handy to add, that I found using tilde 0.4.0

|Key(s)|Action|
|--|--|
|~~ESC~~|~~Close any dialogue~~|
|Left / -|Close dislosure triangle|
|Right / + |Open /expand disclosure triangle|

**Comment by stuaxo** [comment]
Edit:   I realised Escape does work, but I need to hit it twice, I guess this is a side effect of weird unix text terminal stuff, it always bugs me :(

**Comment by gphalkes** [comment]
Whether you have to hit escape twice depends on the settings in Tilde. The default settings do require this, but this is to ensure that Tilde is always usable. I.e. it allows one to reach the menu by pressing Esc first, and then the letter. However, if your terminal allows you to press alt+letter to reach the menus, you can tell Tilde to interpret a single Esc press as "escape" and thus close the window. To do this, go to Options > Input Handling, and unselect "'Esc <letter>' simulates Meta+<letter>.

The other suggestions are definitely useful to implement and shouldn't be difficult to do. I'll have a look at some point to add these.

**Comment by stuaxo** [comment]
Cheers, I found the setting in tilde, I'm starting to use tilde a bit more so will see if any others come up.

**Comment by gphalkes** [comment]
Navigation for the expander widget has been updated to include +/- and right/left arrow for navigation: https://github.com/gphalkes/t3widget/commit/6888906899b8b240feb60716975383cd7d12af22

This will be part of the next libt3widget release.

**Comment by gphalkes** [comment]
A new release (1.1.0) of libt3widget is available, which includes this feature.
