### ISSUE TITLE
Feature request: Support Ctrl-Backspace

### ISSUE THREAD

**Issue by espentveit** [gphalkes/tilde#53]
Just found out about this gem of an editor and was happy to be able to transfer muscle memory shortcuts from various UI editors to the  console 

There is one small thing that may be obscure, that I use quite frequently. The ability to delete a word backwards using Ctrl-Backspace.

It works as a shortcut for select word backwards and delete (Ctrl-Shift-Left arrow and Delete), and makes deleting wrong or mistyped words quickly a breeze.

**Comment by espentveit** [comment]
I'm having a go at implementing this. The editor part works now, but the main key switch statement doesn't intercept Ctrl-Backspace so I'm looking into that,

**Comment by espentveit** [comment]
Made it work. It seems init_keys didn't include modifiers from name when processing single keys.

https://github.com/espentveit/t3widget/commit/248e09cc1c998387e5837c4ea3a314cc2e198043

**Comment by espentveit** [comment]
Made a pull request if you want to include it. No hard feelings if you don't. My main language is not C++ :)

**Comment by gphalkes** [comment]
I left another comment on the pull request, but for completeness I'll repeat it here. I think this is a good addition, and I will have a look at the pull request soon(ish)

**Comment by gphalkes** [comment]
A new release (1.1.0) of libt3widget is available, which includes this feature.
