### ISSUE TITLE
Tilde can't read its config file in byobu, screen or term

### ISSUE THREAD

**Issue by Linguista** [gphalkes/tilde#55]
_What OS are you using (including version):_ 
Ubuntu 18.04 server, Ubuntu 19.04 desktop, KDE Neon 5.16.

_What terminal were you running Tilde on when you ran into the issue:_ Konsole, Tilda, Yakuake, Guake and others.

_Please paste the result of running 'tilde --version':_
```
$ tilde --version
Tilde version 1.0.2
Copyright (c) 2011-2018 G.P. Halkes
Tilde is licensed under the GNU General Public License version 3

Library versions:
  libt3config 1.0.0
  libt3highlight 0.4.9
  libt3key (through libt3widget) 0.2.8
  libt3widget 1.0.6
  libt3window 0.3.2
  libtranscript 0.3.3
  libunistring 9.9.?
```

When using `tilde` _directly in a terminal_, it reads its config file at `~/.config/tilde/config` and my customizations are loaded. New customizations I make are saved here, too. All is working as it should.

However, when using `tilde` inside `byobu`, `screen` or `tmux`, `tilde` does not read its own config file. Furthermore, it cannot load this config file manually, even with the `--config=/path/to/config/file` option. Instead, it acts as if it has never run before -- the default settings are used and `tilde` shows the initial input configuration dialog screen. 

Configuration changes made inside `byobu`, `screen` and `tmux` are then saved and preserved, but _in a different file_ that I cannot locate. I can only confirm that configuration changes made inside these terminal multiplexers are _not_ saved in `~/.config/tilde/config`.

The expected behavior is that `tilde` read its config file at  `~/.config/tilde/config` in all cases.

**Comment by Linguista** [comment]
Very clear explanation. Thanks a lot. For now, I just copied the contents of the config entry for the terminal I customized into the entries for other terminals. Seems to work fine except on my `tmux`, which for whatever reason has less than 256 colors.

And by the way, thanks so much for Tilde -- It's the terminal text editor I've been wanting for YEARS!

**Comment by gphalkes** [comment]
> And by the way, thanks so much for Tilde -- It's the terminal text editor I've been wanting for YEARS!

I got tired of waiting ;-)

As for the tmux issue: have you tried passing the -2 flag to it? I think tmux may have difficulty determining the number of colors the terminal supports, and the -2 flag should force it to assume 256 colors.

**Comment by Linguista** [comment]
The `-2` flag hasn't worked so far for some reason, but this has:

`echo "set -g default-terminal \"screen-256color\"" > ~/.tmux.conf`

It also works with `tmux-256-color`.
