### ISSUE TITLE
Tilde 1.0.2 does not save files if the user has no access rights

### ISSUE THREAD

**Issue by tjaacks** [gphalkes/tilde#57]
When I edit a system file without putting "sudo" in front of tilde, I can edit it, tilde asks if I want to save it on quitting and then successfully quits without a note. The file, however, has not been saved.

Tilde should display an error if a file cannot be saved.

Additionally, tilde could warn the user when opening a file without write access (maybe display some "READ ONLY" message in the status or title bar).

**Comment by gphalkes** [comment]
Thanks for reporting this and I'm terribly sorry for the obviously lost work that this incurred.

I agree that it would be nice to have some warning that the file can't be saved back if the user doesn't have write permissions. I'll add a separate feature request bug for that.

**Comment by gphalkes** [comment]
I've uploaded a new release which fixes the issue.

**Comment by tjaacks** [comment]
Thanks a lot for the quick fix!
