### ISSUE TITLE
Tilde repository is not available for Debian buster

### ISSUE THREAD

**Issue by tjaacks** [gphalkes/tilde#58]
The provided `install_repo.sh` script installs `/etc/apt/sources.list.d/tilde.list` with the following contents:

`deb http://download.opensuse.org/repositories/home:/gphalkes:/tilde/Debian_10.0 ./`

This URL replies "404  Not Found".

**Comment by gphalkes** [comment]
They now have removed the .0 suffix, so I needed to update the repo link. Thanks for the report.
