### ISSUE TITLE
Can't search for non-ASCII characters

### ISSUE THREAD

**Issue by seivadnomis** [gphalkes/tilde#6]
If I search for an everyday Unicode character such as `’` (RIGHT SINGLE QUOTATION MARK) or `é` (LATIN SMALL LETTER E WITH ACUTE), Tilde fails to find it.

Furthermore, Tilde also fails to find an ASCII character located immediately before a Unicode character, such as the first hyphen in `nim-é-nom` (it finds only the second one).

**Comment by gphalkes** [comment]
Thanks for the report. I'll look into it. For now, a work-around is to use regular expression search. This doesn't exhibit the same problem.

**Comment by gphalkes** [comment]
A fix has been committed to the libt3widget repository. I'm currently working on fixing other bugs, but I'll do a new release of libt3widget soon.

**Comment by seivadnomis** [comment]
Thank you for your quick response.
