### ISSUE TITLE
Install scripts in sources.list.d don't support Ubuntu-based distros

### ISSUE THREAD

**Issue by nevillepark** [gphalkes/tilde#62]
Hi, belated thanks for adding Markdown highlighting to tilde! I only realized my version was out-of-date just now, which is the issue.

The scripts `install_repo.sh` and `install_tilde.sh` at https://os.ghalkes.nl/sources.list.d/ include the line `wget --output-document=/etc/apt/sources.list.d/tilde.list http://os.ghalkes.nl/sources.list.d/$(lsb_release -cs).list`

However, this means the script fails for distros that are based on Ubuntu but have different codenames, like Mint and elementary OS. It tries to look up "http://os.ghalkes.nl/sources.list.d/hera.list", which fails, and writes a blank file to `/etc/apt/sources.list.d/tilde.list`.

In the past I edited the files myself to fetch the right URL, which is how I installed it in the first place. But at some point it must have gotten overwritten, which meant I stopped getting tilde updates. 

Some distros have implemented a feature where `lsb_release -csu` will [return the upstream codename](https://blog.sleeplessbeastie.eu/2014/09/30/how-to-check-upstream-distribution-specific-information/), but it's not in [Ubuntu's version](http://manpages.ubuntu.com/manpages/bionic/man1/lsb_release.1.html). So simply changing `lsb_release -cs` to `lsb_release -csu` would then break the script for Ubuntu users.

Would [a solution like this](https://askubuntu.com/a/1015590) work? 

If not, could you add a section in [the instructions on the Download page](https://os.ghalkes.nl/tilde/download.html), providing a different version of the scripts in http://os.ghalkes.nl/sources.list.d/ (e. g. `install_repo_derived.sh`) or just letting users of derivative distros know to add the "u"?

Thanks again.

**Comment by gphalkes** [comment]
Thanks for the suggestion. I've implemented the linked solution, so you should now be able to use the script unmodified.
