### ISSUE TITLE
Feature request: have shift+down and shift+up mark the rest of the line to the same column on the next or previous line

### ISSUE THREAD

**Issue by cheapy** [gphalkes/tilde#63]
I am using antiX 19.1 x_64 (a Debian based distro)

$ tilde --version
Tilde version 1.0.0
Copyright (c) 2011-2018 G.P. Halkes
Tilde is licensed under the GNU General Public License version 3
Library versions:
  libt3config 0.2.11
  libt3highlight 0.4.6
  libt3key (through libt3widget) 0.2.9
  libt3widget 1.0.3
  libt3window 0.3.2
  libtranscript 0.3.3
  libunistring 9.10.?

When I hold down the shift and arrow left or right, it marks or unmarks the text as expected, but the when I hold down the shift and press the up or down arrow it doesn't mark or unmark the rest of the line to the same position (or end of line if shorter) of the previous or next line like most editors do.

I would not consider it a bug, but marking with arrow keys would be a lot more efficient if that feature was incorporated.

**Comment by cheapy** [comment]
I see that Ctrl+T works to mark, and the mouse can mark, so this would be more familiar, but not necessary.  Tilde is definitely my favorite terminal based editor.  Thanks for your efforts on it.

**Comment by cheapy** [comment]
I see that Ctrl+T works to mark, and the mouse can mark, so this would be more familiar, but not necessary.  Tilde is definitely my favorite terminal based editor.  Thanks for your efforts on it.

**Comment by gphalkes** [comment]
Shift+up and shift+down should work. This is likely due to your terminal either not providing the information, or claiming to be xterm while not actually implementing the correct sequences. Could you do the following:

1. provide the result of running the following command 
echo $TERM
2. provide what appears on screen when you run the "cat" command without any arguments and press shift+up and shift+down (press ctrl+c to exit)
3. provide what appears on screen when you run the following and press shift+up and shift+down (press ctrl+c to exit)
tput smkx ; cat
4. run "tput rmkx" or "reset" to restore your terminal to its original settings

**Comment by cheapy** [comment]
bobc@alien:~
$ echo $TERM
xterm
bobc@alien:~
$ cat
^C
bobc@alien:~
$ tput smkx ; cat
^C
bobc@alien:~
$ 

The terminal I'm using is ROXTerm 2.9.5
GTK 2 / VTE 9 build

If there is something I can do to it's configuration to fix this, please let me know

Thanks

**Comment by cheapy** [comment]
Here is the output from xev

bobc@alien:~
$ xev -event keyboard
Outer window is 0x3e00001, inner window is 0x3e00002

KeymapNotify event, serial 20, synthetic NO, window 0x0,
    keys:  87  0   0   0   16  0   0   0   0   0   0   0   0   0   0   0   
           0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   

KeyRelease event, serial 25, synthetic NO, window 0x3e00001,
    root 0x133, subw 0x0, time 85636788, (401,9), root:(402,730),
    state 0x0, keycode 36 (keysym 0xff0d, Return), same_screen YES,
"   XLookupString gives 1 bytes: (0d) "
    XFilterEvent returns: False

KeyPress event, serial 28, synthetic NO, window 0x3e00001,
    root 0x133, subw 0x0, time 85639472, (401,9), root:(402,730),
    state 0x0, keycode 50 (keysym 0xffe1, Shift_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 28, synthetic NO, window 0x3e00001,
    root 0x133, subw 0x0, time 85640491, (401,9), root:(402,730),
    state 0x1, keycode 111 (keysym 0xff52, Up), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 28, synthetic NO, window 0x3e00001,
    root 0x133, subw 0x0, time 85640677, (401,9), root:(402,730),
    state 0x1, keycode 111 (keysym 0xff52, Up), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 28, synthetic NO, window 0x3e00001,
    root 0x133, subw 0x0, time 85643566, (401,9), root:(402,730),
    state 0x1, keycode 116 (keysym 0xff54, Down), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 28, synthetic NO, window 0x3e00001,
    root 0x133, subw 0x0, time 85643753, (401,9), root:(402,730),
    state 0x1, keycode 116 (keysym 0xff54, Down), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 28, synthetic NO, window 0x3e00001,
    root 0x133, subw 0x0, time 85644793, (401,9), root:(402,730),
    state 0x1, keycode 50 (keysym 0xffe1, Shift_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False

ClientMessage event, serial 28, synthetic YES, window 0x3e00001,
    message_type 0x154 (WM_PROTOCOLS), format 32, message 0x151 (WM_DELETE_WINDOW)
bobc@alien:~

**Comment by gphalkes** [comment]
Apologies for the extremely slow response. This dropped of my radar.

Unfortunately, it appears that ROXTerm doesn't send any key sequence to the terminal on pressing shift+up or shift+down. That means that there is nothing Tilde can do. It is possible that ROXTerm can be configured to send the appropriate key sequences (see [here](https://github.com/gphalkes/tilde/issues/63#issuecomment-609397048) for the expected sequences), but I don't know how to do that.

**Comment by cheapy** [comment]
Thanks for the reply.  I've been surviving, but didn't realize that the terminal was the root cause.  Are there any other lightweight terminals that you would suggest I try instead?

My biggest constraints are that I would like to keep my Copy/Paste keys Ctrl-C and Ctrl-V to match my X-Windows applications and MS applications to try to keep some sanity switching between systems all the time, and that some of my systems are pre-2000 antiques that are limited on resources.

**Comment by cheapy** [comment]
Its ok, no need to reply.  I downloaded a number of other lightweight terminal programs.  You are correct that Shift-Down to highlight lines works on most of the others.  ROXTerm was doing well, otherwise.  Thanks for letting me know.
