### ISSUE TITLE
CSS Syntax Highlighting issues

### ISSUE THREAD

**Issue by pufflegamerz** [gphalkes/tilde#66]
OS: Debian 10 + MATE
Version:
Tilde version 1.0.0
Copyright (c) 2011-2018 G.P. Halkes
Tilde is licensed under the GNU General Public License version 3
Library versions:
  libt3config 0.2.11
  libt3highlight 0.4.6
  libt3key (through libt3widget) 0.2.9
  libt3widget 1.0.3
  libt3window 0.3.2
  libtranscript 0.3.3
  libunistring 9.10.?

The file can be found here:
view-source:http://api.heb12.com/ui/index.html
![Screenshot at 2020-07-09 20-01-42](https://user-images.githubusercontent.com/32369330/87102154-0f9ddc80-c21f-11ea-87f2-58528a071345.png)
There is some strange behavior with IDs in CSS, within HTML.
Also, CSS comments aren't recognised.

**Comment by gphalkes** [comment]
Note that the comment issue was already resolved in version libt3highlight 0.5.0.
