### ISSUE TITLE
Seg fault with certain long filenames that don't fit in the status bar

### ISSUE THREAD

**Issue by szc126** [gphalkes/tilde#83]
What OS are you using (including version): `5.15.10-arch1-1`
What terminal were you running Tilde on when you ran into the issue: `alacritty`

Please paste the result of running 'tilde --version':
```
Tilde version 1.1.2
Copyright (c) 2011-2018 G.P. Halkes
Tilde is licensed under the GNU General Public License version 3
Library versions:
  libt3config 1.0.0
  libt3highlight 0.5.0
  libt3key (through libt3widget) 0.2.10
  libt3widget 1.2.0
  libt3window 0.4.0
  libtranscript 0.3.3
  libunistring 9.10.?
```

Please describe the problem. If possible, include the action you performed, the expected result and the actual result in the description.

Tilde segfaults if a path fits the following criteria.
- Does not fit in the status bar, either at startup or upon resizing the terminal window.
- Has CJK (doublewidth?) characters
- Has a `/`
- "Long" (?)
  - `/tmp/aaaaaaaaaaaaa阿阿阿阿阿阿阿阿.txt` will not segfault.
  - `/tmp/aaaaaaaaaaaaaa阿阿阿阿阿阿阿阿.txt` will segfault.
  - `aaaaaaaaaaaaaa阿阿阿阿阿阿阿阿.txt` will not segfault.

**Comment by gphalkes** [comment]
Thanks for the detailed analysis of the issue. I've been able to reproduce it locally, and I will try to look into this soon.
