### ISSUE TITLE
Seg fault when trying to open editor

### ISSUE THREAD

**Issue by jdcard** [gphalkes/tilde#86]
When reporting a bug, please provide the information requested below to aid in the diagnosis of the problem. For feature requests you can remove the template text.

What OS are you using (including version):
  Machine A:
```
Linux JDC2 5.15.16-1-MANJARO #1 SMP PREEMPT Thu Jan 20 13:58:19 UTC 2022 x86_64 GNU/Linux
```
  Machine B: 
```
Linux JDC-PineBookPro 5.16.2-4-MANJARO-ARM #1 SMP PREEMPT Sun Jan 23 23:38:07 UTC 2022 aarch64 GNU/Linux
```

What terminal were you running Tilde on when you ran into the issue: Terminator, but same error occurs in the Linux console.

Please paste the result of running 'tilde --version':
  Machine A: 
```
james@JDC2:~$ tilde --version
Tilde version 1.1.3
Copyright (c) 2011-2018 G.P. Halkes
Tilde is licensed under the GNU General Public License version 3
Library versions:
  libt3config 1.0.0
  libt3highlight 0.5.0
  libt3key (through libt3widget) 0.2.10
  libt3widget 1.2.1
  libt3window 0.4.1
  libtranscript 0.3.3
  libunistring 9.10.?
```
  Machine B: 
```
james@JDC-PineBookPro:~$ tilde --version
Tilde version 1.1.3
Copyright (c) 2011-2018 G.P. Halkes
Tilde is licensed under the GNU General Public License version 3
Library versions:
  libt3config 1.0.0
  libt3highlight 0.5.0
  libt3key (through libt3widget) 0.2.10
  libt3widget 1.2.1
  libt3window 0.4.1
  libtranscript 0.3.3
  libunistring 9.10.?
```
Please describe the problem. If possible, include the action you performed, the expected result and the actual result in the description.

Trying to open tilde for editing results in `Segmentation fault (core dumped)` error message. Both `tilde --version` and `tilde --help` produce the expected results.

On both machines tilde was installed from AUR.

**Comment by hbh-coder** [comment]
Me too...  exactly the same issue. I only installed Tilde last Thursday and used it successfully all day. Today (Monday) is the first time I have tried to run it again, and get the 'segmentation fault (core dumped)' error.

Linux version 5.14.18-100.fc33.x86_64 (mockbuild@bkernel01.iad2.fedoraproject.org) (gcc (GCC) 10.3.1 20210422 (Red Hat 10.3.1-1), GNU ld version 2.35-18.fc33) #1 SMP Fri Nov 12 17:38:44 UTC 2021

Tilde version 1.1.3
Copyright (c) 2011-2018 G.P. Halkes
Tilde is licensed under the GNU General Public License version 3
Library versions:
  libt3config 1.0.0
  libt3highlight 0.5.0
  libt3key (through libt3widget) 0.2.10
  libt3widget 1.2.1
  libt3window 0.4.1
  libtranscript 0.3.3
  libunistring 9.10.?

It's a really great editor - I hope you can get it fixed soon.

**Comment by hbh-coder** [comment]
Don't know if it helps but these all auto-updated for me on Sunday:

tilde-1.1.3-1.1.x86_64                        Sun 30 Jan 2022 06:17:36 AM GMT
libt3window0-0.4.1-1.1.x86_64                 Sun 30 Jan 2022 06:17:36 AM GMT
libt3widget2-1.2.1-1.1.x86_64                 Sun 30 Jan 2022 06:17:36 AM GMT

**Comment by gphalkes** [comment]
Thanks for the report. I've committed a bug fix and will create a release now.

**Comment by jdcard** [comment]
Fix confirmed; working great. Thank you!

**Comment by hbh-coder** [comment]
Yep, likewise it's working for me now.  Thanks!
