### ISSUE TITLE
Why no Ubuntu Focal List?

### ISSUE THREAD

**Issue by jradxl** [gphalkes/tilde#89]
As per this

wget http://os.ghalkes.nl/sources.list.d/install_repo.sh 

followed by...

 sh ./install_repo.sh 
--2022-03-12 14:36:04--  http://os.ghalkes.nl/sources.list.d/focal.list
Resolving os.ghalkes.nl (os.ghalkes.nl)... 178.21.19.64, 2a00:1ca8:2:120::4
Connecting to os.ghalkes.nl (os.ghalkes.nl)|178.21.19.64|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://os.ghalkes.nl/sources.list.d/focal.list [following]
--2022-03-12 14:36:05--  https://os.ghalkes.nl/sources.list.d/focal.list
Connecting to os.ghalkes.nl (os.ghalkes.nl)|178.21.19.64|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-03-12 14:36:05 ERROR 404: Not Found.

**Comment by gphalkes** [comment]
This should be fixed now, along with lists for newer Ubuntu and Mint versions.

There are some issues with builds for the repositories themselves though, which means they latest versions of libt3key aren't available yet. However, the default version in Ubuntu will still be usable, albeit without the latest fixes.
