### ISSUE TITLE
Can't paste text on SSH terminal

### ISSUE THREAD

**Issue by valerian** [gphalkes/tilde#9]
I just discovered Tilde and I think it's great for people who are used to windows key bindings and interface.

However what is quite upsetting is that I couldn't find a way to paste text over SSH: the usual middle click paste (on XTerm) seems to be "hijacked" by tilde, and only pastes from Tilde's internal clipboard instead.

I'm used to do that very often on the terminal or on other editors (Emacs, Vim, Nano), and it's an essential feature of any terminal application.

Are there any workarounds that I could use? Shouldn't there be an option to toggle that?

**Comment by gphalkes** [comment]
There are two ways in which this can be made to work. The first is enabling X forwarding on the SSH session. However, if the SSH connection is not over a local network, this can slow down Tilde when selecting text.

The other option is to hold down shift while pressing the middle mouse button. This tells XTerm not to send a mouse event put to send the text in the paste buffer. Note that if there are newlines in the text to paste, the Tilde automatic indenting might mangle the text. The auto indent can however be disabled in the options menu.

To enable the middle click paste using the middle button without shift would require disabling all mouse support, which may or may not be desirable.

**Comment by valerian** [comment]
Thank you, that was very helpful! Holding down shift works both for pasting and copying.

Being rather often on Windows and using SSH with Cygwin or Putty, I don't think the X forwarding trick would work, though it might with XWin.
