### ISSUE TITLE
Error highlighting for a valid keyword

### ISSUE THREAD

**Issue by prodbywerty** [gphalkes/tilde#90]
# Issue
In a `.js` file, `var` is highlighted as keyword, and modern version `let` is deemed an error. Both are valid keywords.
#
<details><summary><i>Click here for system Info</i></summary>
<p>

gnome-terminal on Ubuntu 21.04, `tilde --version` output is:
```
Tilde version 1.1.2
Copyright (c) 2011-2018 G.P. Halkes
Tilde is licensed under the GNU General Public License version 3
Library versions:
  libt3config 1.0.0
  libt3highlight 0.5.0
  libt3key (through libt3widget) 0.2.10
  libt3widget 1.2.0
  libt3window 0.4.0
  libtranscript 0.3.3
  libunistring 9.10.?
```

</p>
</details>

**Comment by egg4096** [comment]
This applies to `const` too
